### ISSUE TITLE
Add Unit Tests

### ISSUE THREAD

**Issue by growdev** [datafeedr/datafeedr-product-sets#18]
## Overview

This issue includes adding a method for running unit tests on the code to make sure new functionality does not introduce bugs in existing functionality. 

## Description

Testing will be added using [PHPUnit](https://phpunit.de/) since it is the testing framework [chosen by the core team](https://make.wordpress.org/core/handbook/testing/automated-testing/phpunit/). 

A composer file will be added to handle managing required packages and defining scripts for testing.

## Tasks

- [ ] Add `composer.json`.
- [ ] Add `phpunit.xml`.
- [ ] Add setup script
- [ ] Add bootstrap file.
- [ ] Add tests for functions in #14.
